FROM testdasi/pihole-base-buster:latest-rpi4

COPY ./install.sh /

# install cloudflared and run install script
RUN cd /tmp \
    && wget https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-arm.tgz \
    && tar -xvzf ./cloudflared-stable-linux-arm.tgz \
    && cp ./cloudflared /usr/local/bin \
    && rm -f ./cloudflared-stable-linux-arm.tgz \
    && /bin/bash /install.sh \
    && rm -f /install.sh
